# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  Github: https://github.com/dervn
  Wiki: https://dervn.github.io/wiki/
  About: about/
rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
